development: &development
  ev_name: OPENSSL_PASS
  cipher: AES-256-CBC
  options:
    slience: false
    remove_production: false
    remove_source: false
  tasks:
    -
      encrypt_from: config/database.yml
      encrypt_to: config/database.yml.enc
      decrypt_to: config/database.yml
    -
      encrypt_from: config/settings/private_settings/secrets.yml
      encrypt_to: config/settings/private_settings/secrets.yml.enc
      decrypt_to: config/settings/private_settings/secrets.yml
    -
      encrypt_from: config/master.key
      encrypt_to: config/master.key.enc
      decrypt_to: config/master.key
    -
      encrypt_from: config/on_premise_rsa/password/private.pem
      encrypt_to: config/on_premise_rsa/password/private.pem.enc
      decrypt_to: config/on_premise_rsa/password/private.pem
    -
      encrypt_from: config/leveret_auth/ldap.json
      encrypt_to: config/leveret_auth/ldap.json.enc
      decrypt_to: config/leveret_auth/ldap.json

test:
  <<: *development

preparing:
  <<: *development

staging:
  <<: *development

qa:
  <<: *development

production:
  <<: *development
