export const GET_LICENSE = "GET_LICENSE";
export const GET_LICENSE_SUC = "GET_LICENSE_SUC";
export const GET_LICENSE_FAL = "GET_LICENSE_FAL";

export const LICENSE_TYPE = {
  LDAP: "LDAP",
  SYSTEM_CA: "SYSTEM_CA",
  GROUP: "GROUP",
  CHT_CERT: "CHT_CERT",
  SMS: "SMS",
  SMTP: "SMTP",
  CHANGE_SIGNER: "CHANGE_SIGNER",
  DECLINE_TASK: "DECLINE_TASK",
  KIOSK_TASK: "KIOSK_TASK",
  SIGN_VIDEO: "SIGN_VIDEO",
  GROUP_SHARE: "GROUP_SHARE",
  ENTERPRISE_PLAN: "ENTERPRISE_PLAN",
};
