export const SET_SIGNER_SETTINGS_PARAMS = "SET_SIGNER_SETTINGS_PARAMS";
export const CLEAR_SIGNER_SETTINGS_PARAMS = "CLEAR_SIGNER_SETTINGS_PARAMS";
export const SET_SIGNING_GROUP_PARAMS = "SET_SIGNING_GROUP_PARAMS";
export const CLEAR_SIGNING_GROUP_PARAMS = "CLEAR_SIGNING_GROUP_PARAMS";
export const SET_SIGNING_GROUP_IMPORT_PARAMS =
  "SET_SIGNING_GROUP_IMPORT_PARAMS";
export const CLEAR_SIGNING_GROUP_IMPORT_PARAMS =
  "CLEAR_SIGNING_GROUP_IMPORT_PARAMS";
export const SET_AUTO_TASKS_PARAMS = "SET_AUTO_TASKS_PARAMS";
export const CLEAR_AUTO_TASKS_PARAMS = "CLEAR_AUTO_TASKS_PARAMS";
export const SET_SELECTION_TEMPLATES_PARAMS = "SET_SELECTION_TEMPLATES_PARAMS";
export const CLEAR_SELECTION_TEMPLATES_PARAMS =
  "CLEAR_SELECTION_TEMPLATES_PARAMS";
export const SET_SELECTION_WATERMARKS_PARAMS =
  "SET_SELECTION_WATERMARKS_PARAMS";
export const CLEAR_SELECTION_WATERMARKS_PARAMS =
  "CLEAR_SELECTION_WATERMARKS_PARAMS";
export const SET_GROUP_EDIT_PARAMS = "SET_GROUP_EDIT_PARAMS";
export const CLEAR_GROUP_EDIT_PARAMS = "CLEAR_GROUP_EDIT_PARAMS";
export const SET_REPLACE_DOC_PARAMS = "SET_REPLACE_DOC_PARAMS";
export const CLEAR_REPLACE_DOC_PARAMS = "CLEAR_REPLACE_DOC_PARAMS";
export const SET_MODIFY_DOC_PARAMS = "SET_MODIFY_DOC_PARAMS";
export const CLEAR_MODIFY_DOC_PARAMS = "CLEAR_MODIFY_DOC_PARAMS";
export const SET_IS_FIELD_LOST = "SET_IS_FIELD_LOST";
export const SET_MODIFY_FILE_WARNING = "SET_MODIFY_FILE_WARNING";
export const SET_WATERMARK_INFO = "SET_WATERMARK_INFO";
export const SET_MID_VERIFY_FORM_DATA = "SET_MID_VERIFY_FORM_DATA";
export const CLEAR_MID_VERIFY_FORM_DATA = "CLEAR_MID_VERIFY_FORM_DATA";
