export const SET_IS_PUBLIC_FORM = "SET_IS_PUBLIC_FORM";

export const GET_PUBLIC_FORM_ALL = "GET_PUBLIC_FORM_ALL";
export const GET_PUBLIC_FORM_ALL_SUC = "GET_PUBLIC_FORM_ALL_SUC";
export const GET_PUBLIC_FORM_ALL_FAL = "GET_PUBLIC_FORM_ALL_FAL";
export const SET_PUBLIC_FORM_CURRENT_PAGE = "SET_PUBLIC_FORM_CURRENT_PAGE";
export const SET_PUBLIC_FORM_PER_PAGE = "SET_PUBLIC_FORM_PER_PAGE";
export const SET_PUBLIC_FORM_SEARCH_TERM = "SET_PUBLIC_FORM_SEARCH_TERM";
export const DELETE_PUBLIC_FORM = "DELETE_PUBLIC_FORM";
export const DELETE_PUBLIC_FORM_SUC = "DELETE_PUBLIC_FORM_SUC";
export const DELETE_PUBLIC_FORM_FAL = "DELETE_PUBLIC_FORM_FAL";
export const GET_PUBLIC_FORM_CSV = "GET_PUBLIC_FORM_CSV";
export const GET_PUBLIC_FORM_CSV_SUC = "GET_PUBLIC_FORM_CSV_SUC";
export const GET_PUBLIC_FORM_CSV_FAL = "GET_PUBLIC_FORM_CSV_FAL";
export const PUT_PUBLIC_FORM_STATUS = "PUT_PUBLIC_FORM_STATUS";
export const PUT_PUBLIC_FORM_STATUS_SUC = "PUT_PUBLIC_FORM_STATUS_SUC";
export const PUT_PUBLIC_FORM_STATUS_FAL = "PUT_PUBLIC_FORM_STATUS_FAL";
export const POST_COPY_PUBLIC_FORM = "POST_COPY_PUBLIC_FORM";
export const POST_COPY_PUBLIC_FORM_SUC = "POST_COPY_PUBLIC_FORM_SUC";
export const POST_COPY_PUBLIC_FORM_FAL = "POST_COPY_PUBLIC_FORM_FAL";

export const SET_PREVIEW_EMAIL = "SET_PREVIEW_EMAIL";
export const GET_PUBLIC_FORM_PREVIEW = "GET_PUBLIC_FORM_PREVIEW";
export const GET_PUBLIC_FORM_PREVIEW_SUC = "GET_PUBLIC_FORM_PREVIEW_SUC";
export const GET_PUBLIC_FORM_PREVIEW_FAL = "GET_PUBLIC_FORM_PREVIEW_FAL";
export const SET_TAB_ACTIVE = "SET_TAB_ACTIVE";

export const PUT_PUBLIC_FORM_COMPRESS = "PUT_PUBLIC_FORM_COMPRESS";
export const PUT_PUBLIC_FORM_COMPRESS_SUC = "PUT_PUBLIC_FORM_COMPRESS_SUC";
export const PUT_PUBLIC_FORM_COMPRESS_FAL = "PUT_PUBLIC_FORM_COMPRESS_FAL";

export const RESET_PUBLIC_FORM = "RESET_PUBLIC_FORM";

export const UPDATE_PUBLIC_FORM_CONDITION = "UPDATE_PUBLIC_FORM_CONDITION";
