export const SET_MOBILE_PANEL_URL = "SET_MOBILE_PANEL_URL";
export const SET_MOBILE_PANEL_URL_SUC = "SET_MOBILE_PANEL_URL_SUC";
export const SET_MOBILE_PANEL_URL_FAL = "SET_MOBILE_PANEL_URL_FAL";

export const SET_PANEL_STATE = "SET_PANEL_STATE";

export const PANEL_STAGE = {
  QRCODE: "PANEL_STAGE_QRCODE",
  QRCODE_TIMEOUT: "PANEL_STAGE_QRCODE_TIMEOUT",
  SIGN_SUCCESS: "PANEL_STAGE_SIGN_SUCCESS",
  WAIT_REMOTE_SIGN: "WAIT_REMOTE_SIGN",
  SIGN_BROAD: "PANEL_STAGE_SIGN_BROAD",
};
