export const UPDATE_SOCKET_CHANNEL_STATUS = "UPDATE_SOCKET_CHANNEL_STATUS";
export const INITIALIZE_WEB_SOCKETS_CHANNEL = "INITIALIZE_WEB_SOCKETS_CHANNEL";
export const SET_SOCKET_STATUS_COMPLETE = "SET_SOCKET_STATUS_COMPLETE";
export const CLEAR_SOCKET_STATUS_COMPLETE = "CLEAR_SOCKET_STATUS_COMPLETE";
export const ON_CHT_VERIFY_FAL = "ON_CHT_VERIFY_FAL";
export const ON_MSG_EVENT = "ON_MSG_EVENT";
export const EMIT_BROADCAST_EVENT = "EMIT_BROADCAST_EVENT";
export const CLEAR_CHT_RELATED = "CLEAR_CHT_RELATED";

export const CLOSE_SOCKET = "CLOSE_SOCKET";
export const RECONNECT = "RECONNECT";

export const SOCKET_COMMAND_SUBSCRIBE = "SOCKET_COMMAND_SUBSCRIBE";
export const SOCKET_COMMAND_MESSAGE = "SOCKET_COMMAND_MESSAGE";

export const SOCKET_CHANNEL_TYPE_SIGN = "SOCKET_CHANNEL_TYPE_SIGN";
export const SOCKET_CHANNEL_TYPE_MOBILE_PANEL =
  "SOCKET_CHANNEL_TYPE_MOBILE_PANEL";

export const WATCH_FILE_UPLOAD = "WATCH_FILE_UPLOAD";
export const FILE_UPLOAD = "FILE_UPLOAD";
export const FILE_UPLOAD_COMPLETE = "FILE_UPLOAD_COMPLETE";
export const FILE_UPLOAD_RESET = "FILE_UPLOAD_RESET";

export const UPDATE_UPLOAD_CHANNEL_STATUS = "UPDATE_UPLOAD_CHANNEL_STATUS";
export const UPDATE_UPLOAD_CHANNEL_STATUS_SUC =
  "UPDATE_UPLOAD_CHANNEL_STATUS_SUC";
export const UPDATE_UPLOAD_CHANNEL_STATUS_COMPLETE =
  "UPDATE_UPLOAD_CHANNEL_STATUS_COMPLETE";
