export const POSITION = {
  top: "top",
  topRight: "topRight",
  bottom: "bottom",
  bottomRight: "bottomRight",
};

const tooltip = {
  autoReminder: "autoReminder",
  dateExpiration: "dateExpiration",
  otpViaEmail: "otpViaEmail",
  otpViaEmailCreate: "otpViaEmailCreate",
  message: "message",
  returnMessage: "returnMessage",
  attachment: "attachment",
  fileDownload: "fileDownload",
  backTask: "backTask",
  receiverLang: "receiverLang",
  pricingEssentialSigningFields: "pricingEssentialSigningFields",
  pricingEssentialMobileApp: "pricingEssentialMobileApp",
  pricingAdvancedInPerson: "pricingAdvancedInPerson",
  pricingAdvancedSigningFields: "pricingAdvancedSigningFields",
  pricingAdminBranding: "pricingAdminBranding",
  pricingAdminPasswordSms: "pricingAdminPasswordSms",
  pricingAdminAppLock: "pricingAdminAppLock",
  cc: "cc",
  verifyTiming: "verifyTiming",
  defaultValue: "defaultValue",
  placeholder: "placeholder",
  fontSize: "fontSize",
  alignment: "alignment",
  verticalAlignment: "verticalAlignment",
  regex: "regex",
  mobileSignPanel: "mobileSignPanel",
  backgroundRemovalThreshold: "backgroundRemovalThreshold",
  eraserRestoreMode: "eraserRestoreMode",
  emailPerRequest: "emailPerRequest",
  permissionViewUser: "permissionViewUser",
  review: "review",
  publicFormTerminated: "publicFormTerminated",
  publicForm: "publicForm",
  signingGroup: "signingGroup",
  completionPassword: "completionPassword",
  encryptionChtAuthConflict: "encryptionChtAuthConflict",
};

export default tooltip;
